//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace display_Student_Details.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/getStudentId", ReplyAction="http://tempuri.org/IStudentService/getStudentIdResponse")]
        int getStudentId(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/getStudentId", ReplyAction="http://tempuri.org/IStudentService/getStudentIdResponse")]
        System.Threading.Tasks.Task<int> getStudentIdAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/getStudentName", ReplyAction="http://tempuri.org/IStudentService/getStudentNameResponse")]
        string getStudentName(string studentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/getStudentName", ReplyAction="http://tempuri.org/IStudentService/getStudentNameResponse")]
        System.Threading.Tasks.Task<string> getStudentNameAsync(string studentName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : display_Student_Details.ServiceReference3.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<display_Student_Details.ServiceReference3.IStudentService>, display_Student_Details.ServiceReference3.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getStudentId(int studentId) {
            return base.Channel.getStudentId(studentId);
        }
        
        public System.Threading.Tasks.Task<int> getStudentIdAsync(int studentId) {
            return base.Channel.getStudentIdAsync(studentId);
        }
        
        public string getStudentName(string studentName) {
            return base.Channel.getStudentName(studentName);
        }
        
        public System.Threading.Tasks.Task<string> getStudentNameAsync(string studentName) {
            return base.Channel.getStudentNameAsync(studentName);
        }
    }
}
